<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AdditionalInformationTableSeeder extends Seeder
{
    /**
     * Auto generated seed file
     */
    public function run(): void
    {

        DB::table('additional_information')->delete();

        DB::table('additional_information')->insert([
            0 => [
                'id' => 2,
                'name' => 'Appliances',
                'parent_id' => null,
                'created_at' => '2018-05-04 15:50:22',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            1 => [
                'id' => 3,
                'name' => 'Cooling Type',
                'parent_id' => null,
                'created_at' => '2018-05-04 15:50:22',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            2 => [
                'id' => 4,
                'name' => 'Floor Covering',
                'parent_id' => null,
                'created_at' => '2018-06-27 17:18:01',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            3 => [
                'id' => 5,
                'name' => 'Heating Type',
                'parent_id' => null,
                'created_at' => '2018-05-04 15:50:22',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            4 => [
                'id' => 6,
                'name' => 'Heating Fuel',
                'parent_id' => null,
                'created_at' => '2018-06-27 17:18:01',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            5 => [
                'id' => 7,
                'name' => 'Indoor Features',
                'parent_id' => null,
                'created_at' => '2018-05-04 15:50:22',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            6 => [
                'id' => 8,
                'name' => 'Rooms',
                'parent_id' => null,
                'created_at' => '2018-05-04 15:50:22',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            7 => [
                'id' => 9,
                'name' => 'Building/Development Amenities',
                'parent_id' => null,
                'created_at' => '2018-06-27 17:18:01',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            8 => [
                'id' => 10,
                'name' => 'Architectural Style',
                'parent_id' => null,
                'created_at' => '2018-06-27 17:16:27',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            9 => [
                'id' => 11,
                'name' => 'Exterior',
                'parent_id' => null,
                'created_at' => '2018-05-04 15:50:22',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            10 => [
                'id' => 12,
                'name' => 'Outdoor Amenities',
                'parent_id' => null,
                'created_at' => '2018-05-04 15:50:22',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            11 => [
                'id' => 13,
                'name' => 'Parking',
                'parent_id' => null,
                'created_at' => '2018-05-04 15:50:22',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            12 => [
                'id' => 14,
                'name' => 'Roof Type',
                'parent_id' => null,
                'created_at' => '2018-05-04 15:50:22',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            13 => [
                'id' => 15,
                'name' => 'View',
                'parent_id' => null,
                'created_at' => '2018-05-04 15:50:22',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            14 => [
                'id' => 20,
                'name' => 'Dishwasher',
                'parent_id' => 2,
                'created_at' => '2018-05-01 15:20:43',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            15 => [
                'id' => 21,
                'name' => 'Dryer',
                'parent_id' => 2,
                'created_at' => '2018-05-01 15:20:43',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            16 => [
                'id' => 22,
                'name' => 'Freezer',
                'parent_id' => 2,
                'created_at' => '2018-05-01 15:20:43',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            17 => [
                'id' => 23,
                'name' => 'Garbage disposal',
                'parent_id' => 2,
                'created_at' => '2018-05-01 15:20:43',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            18 => [
                'id' => 24,
                'name' => 'Microwave',
                'parent_id' => 2,
                'created_at' => '2018-05-01 15:20:43',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            19 => [
                'id' => 25,
                'name' => 'Range / Oven',
                'parent_id' => 2,
                'created_at' => '2018-05-01 15:20:43',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            20 => [
                'id' => 26,
                'name' => 'Refrigerator',
                'parent_id' => 2,
                'created_at' => '2018-05-01 15:20:43',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            21 => [
                'id' => 27,
                'name' => 'Trash compactor',
                'parent_id' => 2,
                'created_at' => '2018-05-01 15:20:43',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            22 => [
                'id' => 28,
                'name' => 'Washer',
                'parent_id' => 2,
                'created_at' => '2018-05-01 15:20:43',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            23 => [
                'id' => 29,
                'name' => 'Central',
                'parent_id' => 3,
                'created_at' => '2018-05-01 13:26:11',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            24 => [
                'id' => 30,
                'name' => 'Evaporative',
                'parent_id' => 3,
                'created_at' => '2018-05-01 15:20:43',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            25 => [
                'id' => 31,
                'name' => 'Geothermal',
                'parent_id' => 3,
                'created_at' => '2018-05-01 15:20:43',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            26 => [
                'id' => 32,
                'name' => 'Refrigeration',
                'parent_id' => 3,
                'created_at' => '2018-05-01 15:20:43',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            27 => [
                'id' => 33,
                'name' => 'Solar',
                'parent_id' => 3,
                'created_at' => '2018-05-01 15:20:43',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            28 => [
                'id' => 34,
                'name' => 'Wall',
                'parent_id' => 3,
                'created_at' => '2018-05-01 15:20:43',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            29 => [
                'id' => 35,
                'name' => 'Other',
                'parent_id' => 3,
                'created_at' => '2018-05-01 15:20:43',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            30 => [
                'id' => 36,
                'name' => 'None',
                'parent_id' => 3,
                'created_at' => '2018-05-01 15:20:43',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            31 => [
                'id' => 37,
                'name' => 'Carpet',
                'parent_id' => 4,
                'created_at' => '2018-05-01 15:20:43',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            32 => [
                'id' => 38,
                'name' => 'Concrete',
                'parent_id' => 4,
                'created_at' => '2018-05-01 15:20:43',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            33 => [
                'id' => 39,
                'name' => 'Hardwood',
                'parent_id' => 4,
                'created_at' => '2018-05-01 15:20:43',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            34 => [
                'id' => 40,
                'name' => 'Laminate',
                'parent_id' => 4,
                'created_at' => '2018-05-01 15:22:07',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            35 => [
                'id' => 41,
                'name' => 'Linoleum/Vinyl',
                'parent_id' => 4,
                'created_at' => '2018-05-01 15:22:07',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            36 => [
                'id' => 42,
                'name' => 'Slate',
                'parent_id' => 4,
                'created_at' => '2018-05-01 15:22:07',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            37 => [
                'id' => 43,
                'name' => 'Softwood',
                'parent_id' => 4,
                'created_at' => '2018-05-01 15:22:08',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            38 => [
                'id' => 44,
                'name' => 'Tile',
                'parent_id' => 4,
                'created_at' => '2018-05-01 15:22:08',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            39 => [
                'id' => 45,
                'name' => 'Other',
                'parent_id' => 4,
                'created_at' => '2018-05-01 15:22:08',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            40 => [
                'id' => 46,
                'name' => 'Baseboard',
                'parent_id' => 5,
                'created_at' => '2018-05-01 15:22:08',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            41 => [
                'id' => 47,
                'name' => 'Forced Air',
                'parent_id' => 5,
                'created_at' => '2018-05-01 15:22:08',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            42 => [
                'id' => 48,
                'name' => 'Heat Pump',
                'parent_id' => 5,
                'created_at' => '2018-05-01 15:22:08',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            43 => [
                'id' => 49,
                'name' => 'Radiant',
                'parent_id' => 5,
                'created_at' => '2018-05-01 15:22:08',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            44 => [
                'id' => 50,
                'name' => 'Stove',
                'parent_id' => 5,
                'created_at' => '2018-09-24 16:36:32',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            45 => [
                'id' => 51,
                'name' => 'Wall',
                'parent_id' => 5,
                'created_at' => '2018-05-01 15:27:31',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            46 => [
                'id' => 52,
                'name' => 'Other',
                'parent_id' => 5,
                'created_at' => '2018-05-01 15:27:31',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            47 => [
                'id' => 53,
                'name' => 'Coal',
                'parent_id' => 6,
                'created_at' => '2018-05-01 15:27:31',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            48 => [
                'id' => 54,
                'name' => 'Electric',
                'parent_id' => 6,
                'created_at' => '2018-05-01 15:27:31',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            49 => [
                'id' => 55,
                'name' => 'Gas',
                'parent_id' => 6,
                'created_at' => '2018-05-01 15:27:31',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            50 => [
                'id' => 56,
                'name' => 'Oil',
                'parent_id' => 6,
                'created_at' => '2018-05-01 15:27:31',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            51 => [
                'id' => 57,
                'name' => 'Propane / butane',
                'parent_id' => 6,
                'created_at' => '2018-05-01 15:27:31',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            52 => [
                'id' => 58,
                'name' => 'Solor',
                'parent_id' => 6,
                'created_at' => '2018-05-01 15:27:31',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            53 => [
                'id' => 59,
                'name' => 'Wood / Pellet',
                'parent_id' => 6,
                'created_at' => '2018-05-01 15:27:31',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            54 => [
                'id' => 60,
                'name' => 'Other',
                'parent_id' => 6,
                'created_at' => '2018-05-01 15:27:31',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            55 => [
                'id' => 61,
                'name' => 'None',
                'parent_id' => 6,
                'created_at' => '2018-05-01 15:27:31',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            56 => [
                'id' => 62,
                'name' => 'Attic',
                'parent_id' => 7,
                'created_at' => '2018-05-01 13:35:08',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            57 => [
                'id' => 63,
                'name' => 'Cable Ready',
                'parent_id' => 7,
                'created_at' => '2018-05-01 15:27:31',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            58 => [
                'id' => 64,
                'name' => 'Ceiling Fans',
                'parent_id' => 7,
                'created_at' => '2018-05-01 15:27:31',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            59 => [
                'id' => 65,
                'name' => 'Fireplace',
                'parent_id' => 7,
                'created_at' => '2018-05-01 15:27:31',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            60 => [
                'id' => 66,
                'name' => 'Intercom System',
                'parent_id' => 7,
                'created_at' => '2018-05-01 15:27:31',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            61 => [
                'id' => 67,
                'name' => 'Jetted Jub',
                'parent_id' => 7,
                'created_at' => '2018-05-01 15:27:31',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            62 => [
                'id' => 68,
                'name' => 'Security System',
                'parent_id' => 7,
                'created_at' => '2018-05-01 15:27:31',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            63 => [
                'id' => 69,
                'name' => 'Skylights',
                'parent_id' => 7,
                'created_at' => '2018-05-01 15:27:31',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            64 => [
                'id' => 70,
                'name' => 'Vaulted Ceiling',
                'parent_id' => 7,
                'created_at' => '2018-05-01 15:27:31',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            65 => [
                'id' => 71,
                'name' => 'Wet Bar',
                'parent_id' => 7,
                'created_at' => '2018-05-01 15:27:31',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            66 => [
                'id' => 72,
                'name' => 'Wired',
                'parent_id' => 7,
                'created_at' => '2018-05-01 15:27:31',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            67 => [
                'id' => 73,
                'name' => 'Double Pane / storm Windows',
                'parent_id' => 7,
                'created_at' => '2018-05-01 15:27:31',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            68 => [
                'id' => 74,
                'name' => 'Mother In Law Apartment',
                'parent_id' => 7,
                'created_at' => '2018-05-01 15:27:31',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            69 => [
                'id' => 75,
                'name' => 'Breakfast Nook',
                'parent_id' => 8,
                'created_at' => '2018-05-01 15:27:31',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            70 => [
                'id' => 76,
                'name' => 'Dining Room',
                'parent_id' => 8,
                'created_at' => '2018-05-01 15:27:31',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            71 => [
                'id' => 77,
                'name' => 'Family Room',
                'parent_id' => 8,
                'created_at' => '2018-05-01 15:27:31',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            72 => [
                'id' => 78,
                'name' => 'Laundry Room',
                'parent_id' => 8,
                'created_at' => '2018-05-01 15:27:31',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            73 => [
                'id' => 79,
                'name' => 'Library',
                'parent_id' => 8,
                'created_at' => '2018-05-01 15:27:31',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            74 => [
                'id' => 80,
                'name' => 'Master Bath',
                'parent_id' => 8,
                'created_at' => '2018-05-01 15:27:31',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            75 => [
                'id' => 81,
                'name' => 'Mud Room',
                'parent_id' => 8,
                'created_at' => '2018-05-01 15:27:31',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            76 => [
                'id' => 82,
                'name' => 'Office',
                'parent_id' => 8,
                'created_at' => '2018-05-01 15:27:31',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            77 => [
                'id' => 83,
                'name' => 'Pantry',
                'parent_id' => 8,
                'created_at' => '2018-05-01 15:27:31',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            78 => [
                'id' => 84,
                'name' => 'Recreation Room',
                'parent_id' => 8,
                'created_at' => '2018-05-01 15:27:31',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            79 => [
                'id' => 85,
                'name' => 'Workshop',
                'parent_id' => 8,
                'created_at' => '2018-05-01 15:27:31',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            80 => [
                'id' => 86,
                'name' => 'Solarium / Atrium',
                'parent_id' => 8,
                'created_at' => '2018-05-01 15:27:32',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            81 => [
                'id' => 87,
                'name' => 'Sun Room',
                'parent_id' => 8,
                'created_at' => '2018-05-01 15:27:32',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            82 => [
                'id' => 88,
                'name' => 'Walk In Closet',
                'parent_id' => 8,
                'created_at' => '2018-05-01 15:27:32',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            83 => [
                'id' => 89,
                'name' => 'Basketball Court',
                'parent_id' => 9,
                'created_at' => '2018-05-01 15:27:32',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            84 => [
                'id' => 90,
                'name' => 'Controlled Access',
                'parent_id' => 9,
                'created_at' => '2018-05-01 15:27:32',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            85 => [
                'id' => 91,
                'name' => 'Disabled Access',
                'parent_id' => 9,
                'created_at' => '2018-05-01 15:27:32',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            86 => [
                'id' => 92,
                'name' => 'Doorman',
                'parent_id' => 9,
                'created_at' => '2018-05-01 15:27:32',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            87 => [
                'id' => 93,
                'name' => 'Elevator',
                'parent_id' => 9,
                'created_at' => '2018-05-01 15:27:32',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            88 => [
                'id' => 94,
                'name' => 'Fitness Center',
                'parent_id' => 9,
                'created_at' => '2018-05-01 15:27:32',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            89 => [
                'id' => 95,
                'name' => 'Gated Entry',
                'parent_id' => 9,
                'created_at' => '2018-05-01 15:27:32',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            90 => [
                'id' => 96,
                'name' => 'Sports Court',
                'parent_id' => 9,
                'created_at' => '2018-05-01 15:27:32',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            91 => [
                'id' => 97,
                'name' => 'Storage',
                'parent_id' => 9,
                'created_at' => '2018-05-01 15:27:32',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            92 => [
                'id' => 98,
                'name' => 'Tennis Court',
                'parent_id' => 9,
                'created_at' => '2018-05-01 15:27:32',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            93 => [
                'id' => 99,
                'name' => 'Assisted Living Community',
                'parent_id' => 9,
                'created_at' => '2018-05-01 15:27:32',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            94 => [
                'id' => 100,
                'name' => 'Over 55+ Active Community',
                'parent_id' => 9,
                'created_at' => '2018-05-01 15:27:32',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            95 => [
                'id' => 101,
                'name' => 'Near Transportation',
                'parent_id' => 9,
                'created_at' => '2018-05-01 15:29:47',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            96 => [
                'id' => 102,
                'name' => 'Bungalow',
                'parent_id' => 10,
                'created_at' => '2018-05-01 15:29:47',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            97 => [
                'id' => 103,
                'name' => 'Cape Cod',
                'parent_id' => 10,
                'created_at' => '2018-05-01 15:29:47',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            98 => [
                'id' => 104,
                'name' => 'Colonial',
                'parent_id' => 10,
                'created_at' => '2018-05-01 15:29:47',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            99 => [
                'id' => 105,
                'name' => 'Contemporary',
                'parent_id' => 10,
                'created_at' => '2018-05-01 15:29:47',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            100 => [
                'id' => 106,
                'name' => 'Craftsman',
                'parent_id' => 10,
                'created_at' => '2018-05-01 15:29:47',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            101 => [
                'id' => 107,
                'name' => 'French',
                'parent_id' => 10,
                'created_at' => '2018-05-01 15:29:47',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            102 => [
                'id' => 108,
                'name' => 'Georgian',
                'parent_id' => 10,
                'created_at' => '2018-05-01 15:29:47',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            103 => [
                'id' => 109,
                'name' => 'Loft',
                'parent_id' => 10,
                'created_at' => '2018-05-01 15:29:47',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            104 => [
                'id' => 110,
                'name' => 'Modern',
                'parent_id' => 10,
                'created_at' => '2018-05-01 15:29:47',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            105 => [
                'id' => 111,
                'name' => 'Ranch / Rambler',
                'parent_id' => 10,
                'created_at' => '2018-05-01 15:29:47',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            106 => [
                'id' => 112,
                'name' => 'Spanish',
                'parent_id' => 10,
                'created_at' => '2018-05-01 15:29:47',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            107 => [
                'id' => 113,
                'name' => 'Split Level',
                'parent_id' => 10,
                'created_at' => '2018-05-01 15:29:47',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            108 => [
                'id' => 114,
                'name' => 'Tudor',
                'parent_id' => 10,
                'created_at' => '2018-05-01 15:29:47',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            109 => [
                'id' => 115,
                'name' => 'Other',
                'parent_id' => 10,
                'created_at' => '2018-05-01 15:29:47',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            110 => [
                'id' => 116,
                'name' => 'Queen Anne / Victorian',
                'parent_id' => 10,
                'created_at' => '2018-05-01 15:29:47',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            111 => [
                'id' => 117,
                'name' => 'Santa Fe / Pueblo Style',
                'parent_id' => 10,
                'created_at' => '2018-05-01 15:09:50',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            112 => [
                'id' => 118,
                'name' => 'Brick',
                'parent_id' => 11,
                'created_at' => '2018-05-01 15:10:05',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            113 => [
                'id' => 119,
                'name' => 'Cement / Concrete',
                'parent_id' => 11,
                'created_at' => '2018-05-01 15:10:14',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            114 => [
                'id' => 120,
                'name' => 'Composition',
                'parent_id' => 11,
                'created_at' => '2018-05-01 15:10:23',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            115 => [
                'id' => 121,
                'name' => 'Metal',
                'parent_id' => 11,
                'created_at' => '2018-05-01 15:10:32',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            116 => [
                'id' => 122,
                'name' => 'Shingle',
                'parent_id' => 11,
                'created_at' => '2018-05-01 15:10:40',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            117 => [
                'id' => 123,
                'name' => 'Stone',
                'parent_id' => 11,
                'created_at' => '2018-05-01 15:10:47',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            118 => [
                'id' => 124,
                'name' => 'Stucco',
                'parent_id' => 11,
                'created_at' => '2018-05-01 15:10:55',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            119 => [
                'id' => 125,
                'name' => 'Vinyl',
                'parent_id' => 11,
                'created_at' => '2018-05-01 15:11:04',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            120 => [
                'id' => 126,
                'name' => 'Wood',
                'parent_id' => 11,
                'created_at' => '2018-05-01 15:11:13',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            121 => [
                'id' => 127,
                'name' => 'Wood products',
                'parent_id' => 11,
                'created_at' => '2018-05-01 15:11:24',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            122 => [
                'id' => 128,
                'name' => 'Other',
                'parent_id' => 11,
                'created_at' => '2018-05-01 15:11:39',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            123 => [
                'id' => 129,
                'name' => 'Balcony/patio',
                'parent_id' => 12,
                'created_at' => '2018-05-01 15:12:04',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            124 => [
                'id' => 130,
                'name' => 'Barbecue area',
                'parent_id' => 12,
                'created_at' => '2018-05-01 15:12:17',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            125 => [
                'id' => 131,
                'name' => 'Deck',
                'parent_id' => 12,
                'created_at' => '2018-05-01 15:12:23',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            126 => [
                'id' => 132,
                'name' => 'Dock',
                'parent_id' => 12,
                'created_at' => '2018-05-01 15:12:33',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            127 => [
                'id' => 133,
                'name' => 'Fenced yard',
                'parent_id' => 12,
                'created_at' => '2018-05-01 15:12:40',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            128 => [
                'id' => 134,
                'name' => 'Garden',
                'parent_id' => 12,
                'created_at' => '2018-05-01 15:12:49',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            129 => [
                'id' => 135,
                'name' => 'Greenhouse',
                'parent_id' => 12,
                'created_at' => '2018-05-01 15:12:57',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            130 => [
                'id' => 136,
                'name' => 'Hot tub/spa',
                'parent_id' => 12,
                'created_at' => '2018-05-01 15:13:07',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            131 => [
                'id' => 137,
                'name' => 'Lawn',
                'parent_id' => 12,
                'created_at' => '2018-05-01 15:13:14',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            132 => [
                'id' => 138,
                'name' => 'Pond',
                'parent_id' => 12,
                'created_at' => '2018-05-01 15:13:22',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            133 => [
                'id' => 139,
                'name' => 'Pool',
                'parent_id' => 12,
                'created_at' => '2018-05-01 15:13:30',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            134 => [
                'id' => 140,
                'name' => 'Porch',
                'parent_id' => 12,
                'created_at' => '2018-05-01 15:13:38',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            135 => [
                'id' => 141,
                'name' => 'RV parking',
                'parent_id' => 12,
                'created_at' => '2018-05-01 15:13:49',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            136 => [
                'id' => 142,
                'name' => 'Sauna',
                'parent_id' => 12,
                'created_at' => '2018-05-01 15:14:05',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            137 => [
                'id' => 143,
                'name' => 'Sprinkler system',
                'parent_id' => 12,
                'created_at' => '2018-05-01 15:14:12',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            138 => [
                'id' => 144,
                'name' => 'Waterfront',
                'parent_id' => 12,
                'created_at' => '2018-05-01 15:14:20',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            139 => [
                'id' => 145,
                'name' => 'Carport',
                'parent_id' => 13,
                'created_at' => '2018-05-01 15:14:31',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            140 => [
                'id' => 146,
                'name' => 'Garage - Attached',
                'parent_id' => 13,
                'created_at' => '2018-05-01 15:14:41',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            141 => [
                'id' => 147,
                'name' => 'Garage - Detached',
                'parent_id' => 13,
                'created_at' => '2018-05-01 15:14:51',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            142 => [
                'id' => 148,
                'name' => 'Off-street',
                'parent_id' => 13,
                'created_at' => '2018-05-01 15:15:01',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            143 => [
                'id' => 149,
                'name' => 'On-street',
                'parent_id' => 13,
                'created_at' => '2018-05-01 15:15:14',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            144 => [
                'id' => 150,
                'name' => 'None',
                'parent_id' => 13,
                'created_at' => '2018-05-01 15:15:22',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            145 => [
                'id' => 151,
                'name' => 'Asphalt',
                'parent_id' => 14,
                'created_at' => '2018-05-01 15:15:34',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            146 => [
                'id' => 152,
                'name' => 'Built-up',
                'parent_id' => 14,
                'created_at' => '2018-05-01 15:15:42',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            147 => [
                'id' => 153,
                'name' => 'Composition',
                'parent_id' => 14,
                'created_at' => '2018-05-01 15:15:51',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            148 => [
                'id' => 154,
                'name' => 'Metal',
                'parent_id' => 14,
                'created_at' => '2018-05-01 15:16:03',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            149 => [
                'id' => 155,
                'name' => 'Shake / Shingle',
                'parent_id' => 14,
                'created_at' => '2018-05-01 15:16:12',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            150 => [
                'id' => 156,
                'name' => 'Slate',
                'parent_id' => 14,
                'created_at' => '2018-05-01 15:16:20',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            151 => [
                'id' => 157,
                'name' => 'Tile',
                'parent_id' => 14,
                'created_at' => '2018-05-01 15:16:28',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            152 => [
                'id' => 158,
                'name' => 'Other',
                'parent_id' => 14,
                'created_at' => '2018-05-01 15:16:37',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            153 => [
                'id' => 159,
                'name' => 'City',
                'parent_id' => 15,
                'created_at' => '2018-05-01 15:16:46',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            154 => [
                'id' => 160,
                'name' => 'Mountain',
                'parent_id' => 15,
                'created_at' => '2018-05-01 15:17:00',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            155 => [
                'id' => 161,
                'name' => 'Park',
                'parent_id' => 15,
                'created_at' => '2018-05-01 15:17:16',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            156 => [
                'id' => 162,
                'name' => 'Territorial',
                'parent_id' => 15,
                'created_at' => '2018-05-01 15:17:23',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            157 => [
                'id' => 163,
                'name' => 'Water',
                'parent_id' => 15,
                'created_at' => '2018-05-01 15:17:31',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            158 => [
                'id' => 164,
                'name' => 'None',
                'parent_id' => 15,
                'created_at' => '2018-05-01 15:17:41',
                'updated_at' => null,
                'deleted_at' => null,
            ],
        ]);

    }
}
