<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ServicesTableSeeder extends Seeder
{
    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run(): void
    {

        DB::table('services')->delete();

        DB::table('services')->insert([
            0 => [
                'id' => 1,
                'industry_id' => 1,
                'service' => 'Title Insurance',
                'created_at' => '2019-02-01 14:56:00',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            1 => [
                'id' => 3,
                'industry_id' => 4,
                'service' => 'Closing Attorney',
                'created_at' => '2019-02-01 14:56:00',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            2 => [
                'id' => 4,
                'industry_id' => 3,
                'service' => 'Homebuyer Counseling',
                'created_at' => '2019-02-01 14:56:00',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            3 => [
                'id' => 5,
                'industry_id' => 3,
                'service' => 'Notary Services',
                'created_at' => '2019-02-01 14:56:00',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            4 => [
                'id' => 6,
                'industry_id' => 7,
                'service' => '203k Consulting',
                'created_at' => '2019-02-01 14:56:00',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            5 => [
                'id' => 7,
                'industry_id' => 4,
                'service' => 'Transaction Coordinator Services',
                'created_at' => '2019-02-01 14:56:00',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            6 => [
                'id' => 9,
                'industry_id' => 5,
                'service' => 'Chimney Inspection',
                'created_at' => '2019-02-01 14:56:00',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            7 => [
                'id' => 10,
                'industry_id' => 5,
                'service' => 'EIFS Inspection',
                'created_at' => '2019-02-01 14:56:00',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            8 => [
                'id' => 14,
                'industry_id' => 5,
                'service' => 'Mold Inspection',
                'created_at' => '2019-02-01 14:56:00',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            9 => [
                'id' => 15,
                'industry_id' => 5,
                'service' => 'Pest Inspection44',
                'created_at' => '2019-02-01 14:56:00',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            10 => [
                'id' => 16,
                'industry_id' => 5,
                'service' => 'Plumbing Inspection',
                'created_at' => '2019-02-01 14:56:00',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            11 => [
                'id' => 17,
                'industry_id' => 5,
                'service' => 'Pool and Spa Inspection',
                'created_at' => '2019-02-01 14:56:00',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            12 => [
                'id' => 18,
                'industry_id' => 5,
                'service' => 'Radon Inspection',
                'created_at' => '2019-02-01 14:56:00',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            13 => [
                'id' => 19,
                'industry_id' => 5,
                'service' => 'Roof Inspection',
                'created_at' => '2019-02-01 14:56:00',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            14 => [
                'id' => 20,
                'industry_id' => 5,
                'service' => 'Septic Inspection',
                'created_at' => '2019-02-01 14:56:00',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            15 => [
                'id' => 21,
                'industry_id' => 5,
                'service' => 'Thermal Inspection',
                'created_at' => '2019-02-01 14:56:00',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            16 => [
                'id' => 22,
                'industry_id' => 5,
                'service' => 'Underground Storage Tank Inspection',
                'created_at' => '2019-02-01 14:56:00',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            17 => [
                'id' => 23,
                'industry_id' => 5,
                'service' => 'Water Quality Inspection',
                'created_at' => '2019-02-01 14:56:00',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            18 => [
                'id' => 24,
                'industry_id' => 5,
                'service' => 'Well Inspection',
                'created_at' => '2019-02-01 14:56:00',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            19 => [
                'id' => 25,
                'industry_id' => 6,
                'service' => 'Land Survey',
                'created_at' => '2019-02-01 14:56:00',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            20 => [
                'id' => 26,
                'industry_id' => 7,
                'service' => 'Structural',
                'created_at' => '2019-02-01 14:56:00',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            21 => [
                'id' => 27,
                'industry_id' => 7,
                'service' => 'Geotechnical',
                'created_at' => '2019-02-01 14:56:00',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            22 => [
                'id' => 28,
                'industry_id' => 8,
                'service' => 'Flood Insurance',
                'created_at' => '2019-02-01 14:56:00',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            23 => [
                'id' => 29,
                'industry_id' => 8,
                'service' => 'Home Insurance',
                'created_at' => '2019-02-01 14:56:00',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            24 => [
                'id' => 30,
                'industry_id' => 9,
                'service' => 'Home Warranty',
                'created_at' => '2019-02-01 14:56:00',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            25 => [
                'id' => 31,
                'industry_id' => 10,
                'service' => 'Yard Design',
                'created_at' => '2019-02-01 14:56:00',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            26 => [
                'id' => 32,
                'industry_id' => 10,
                'service' => 'Yard Maintenance',
                'created_at' => '2019-02-01 14:56:00',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            27 => [
                'id' => 33,
                'industry_id' => 4,
                'service' => 'Tree Removal',
                'created_at' => '2019-02-01 14:56:00',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            28 => [
                'id' => 34,
                'industry_id' => 5,
                'service' => 'Stump Grinding',
                'created_at' => '2019-02-01 14:56:00',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            29 => [
                'id' => 35,
                'industry_id' => 12,
                'service' => 'Certified Public Accountants',
                'created_at' => '2019-02-01 14:56:00',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            30 => [
                'id' => 36,
                'industry_id' => 12,
                'service' => 'Financial Planning',
                'created_at' => '2019-02-01 14:56:00',
                'updated_at' => '2019-04-04 13:49:40',
                'deleted_at' => null,
            ],
            31 => [
                'id' => 37,
                'industry_id' => 13,
                'service' => 'Photographer',
                'created_at' => '2019-02-01 14:56:00',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            32 => [
                'id' => 38,
                'industry_id' => 13,
                'service' => 'Interior Design',
                'created_at' => '2019-02-01 14:56:00',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            33 => [
                'id' => 39,
                'industry_id' => 13,
                'service' => 'Print Media',
                'created_at' => '2019-02-01 14:56:00',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            34 => [
                'id' => 40,
                'industry_id' => 13,
                'service' => 'Web Services',
                'created_at' => '2019-02-01 14:56:00',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            35 => [
                'id' => 41,
                'industry_id' => 13,
                'service' => 'Real Estate Agent',
                'created_at' => '2019-02-01 14:56:00',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            36 => [
                'id' => 42,
                'industry_id' => 13,
                'service' => 'Other',
                'created_at' => '2019-02-01 14:56:00',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            37 => [
                'id' => 43,
                'industry_id' => 14,
                'service' => 'Fencing',
                'created_at' => '2019-02-01 14:56:00',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            38 => [
                'id' => 44,
                'industry_id' => 14,
                'service' => 'Roofing',
                'created_at' => '2019-02-01 14:56:00',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            39 => [
                'id' => 45,
                'industry_id' => 14,
                'service' => 'Masonry',
                'created_at' => '2019-02-01 14:56:00',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            40 => [
                'id' => 46,
                'industry_id' => 14,
                'service' => 'Windows',
                'created_at' => '2019-02-01 14:56:00',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            41 => [
                'id' => 47,
                'industry_id' => 14,
                'service' => 'Vinyl Siding',
                'created_at' => '2019-02-01 14:56:00',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            42 => [
                'id' => 48,
                'industry_id' => 14,
                'service' => 'Gutters',
                'created_at' => '2019-02-01 14:56:00',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            43 => [
                'id' => 49,
                'industry_id' => 14,
                'service' => 'Plumbing',
                'created_at' => '2019-02-01 14:56:00',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            44 => [
                'id' => 50,
                'industry_id' => 14,
                'service' => 'Climate Control',
                'created_at' => '2019-02-01 14:56:00',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            45 => [
                'id' => 51,
                'industry_id' => 14,
                'service' => 'Flooring',
                'created_at' => '2019-02-01 14:56:00',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            46 => [
                'id' => 52,
                'industry_id' => 14,
                'service' => 'Handy-Man',
                'created_at' => '2019-02-01 14:56:00',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            47 => [
                'id' => 53,
                'industry_id' => 14,
                'service' => 'Property Manager',
                'created_at' => '2019-02-01 14:56:00',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            48 => [
                'id' => 54,
                'industry_id' => 16,
                'service' => 'Background Check',
                'created_at' => '2019-02-01 14:56:00',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            49 => [
                'id' => 55,
                'industry_id' => 16,
                'service' => 'Credit Check',
                'created_at' => '2019-02-01 14:56:00',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            50 => [
                'id' => 56,
                'industry_id' => 17,
                'service' => 'Appraiser',
                'created_at' => '2019-02-01 14:56:00',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            51 => [
                'id' => 57,
                'industry_id' => 18,
                'service' => 'Mortgage Lender',
                'created_at' => '2019-02-01 14:56:00',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            52 => [
                'id' => 58,
                'industry_id' => 18,
                'service' => 'VA/FHA Approved Lender',
                'created_at' => '2019-02-01 14:56:00',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            53 => [
                'id' => 59,
                'industry_id' => 13,
                'service' => 'Property Management',
                'created_at' => '2019-02-01 14:56:00',
                'updated_at' => null,
                'deleted_at' => null,
            ],
        ]);

    }
}
