<?php

return[
    'image_count' => 10,
    'year_built' => 1978,
    'property_image_path' => 'app/public/property_images/',
    'profile_images_path' => 'app/public/profile_images/',
    'document_path' => 'app/public/documents/',
    'pagination_count' => 4,
    'backend_item_count' => 10,
    'common_pagination' => 10,
    'property_status' => [
        1 => 'Rented',
        2 => 'Available',
        3 => 'Sold',
        4 => 'In Progress',
        5 => 'Unavailable',
    ],
    'inverse_property_status' => [
        'Rented' => 1,
        'Available' => 2,
        'Sold' => 3,
        'In Progress' => 4,
        'Unavailable' => 5,
    ],
    'interests' => [
        0 => 'Buying',
        1 => 'Selling',
        2 => 'Renting',
        3 => 'Leasing',
        4 => 'Timeshare rentals',
    ],
    'inverse_interests' => [
        'Buying' => 0,
        'Selling' => 1,
        'Renting' => 2,
        'Leasing' => 3,
        'Timeshare rentals' => 4,
    ],
    'share_profile' => [
        1 => 'Yes',
        0 => 'No',
    ],
    'inverse_share_profile' => [
        'Yes' => 1,
        'No' => 0,
    ],
    'loan_status' => [
        0 => 'Not Approved',
        1 => 'Pre-approved',
        2 => 'Pre-qualified',
    ],
    'inverse_loan_status' => [
        'Not Approved' => 0,
        'Pre-approved' => 1,
        'Pre-qualified' => 2,
    ],
    'user_type' => [
        1 => 'Administrator',
        2 => 'Business',
        3 => 'User',
        4 => 'Support',
    ],
    'inverse_user_type' => [
        'Administrator' => 1,
        'Business' => 2,
        'User' => 3,
        'Support' => 4,
    ],
    'industry' => [
        0 => 'Title & Settlement (Closing)',
        1 => 'Attorney',
        2 => 'Consultants & Administrative',
        3 => 'Transaction Coordinator',
        4 => 'Inspection',
        5 => 'Surveyors',
        6 => 'Engineering',
        7 => 'Insurance',
        8 => 'Warranty',
        9 => 'Landscaping',
        10 => 'Arborist (Tree Service)',
        11 => 'Accounting & Tax',
        12 => 'Marketing',
        13 => 'Home Contractor',
        14 => 'Property Management',
        15 => 'Background/Credit Check',
        16 => 'Appraiser',
        17 => 'Mortgage and Lending',
    ],
    'area_of_service' => [
        1 => '10 Miles',
        2 => '25 Miles',
        3 => '50 Miles',
        4 => '100 Miles',
    ],
    'inverse_area_of_service' => [
        '10 Miles' => 1,
        '25 Miles' => 2,
        '50 Miles' => 3,
        '100 Miles' => 4,
    ],
    'property_type' => [
        1 => 'Rent',
        2 => 'Sale',
        3 => 'Vacation',
    ],
    'inverse_property_type' => [
        'Rent' => 1,
        'Sale' => 2,
        'Vacation' => 3,
    ],
    'pets_welcome' => [
        1 => 'Yes',
        0 => 'No',
    ],
    'inverse_pets_welcome' => [
        'Yes' => 1,
        'No' => 0,
    ],
    'display_phone' => [
        1 => 'Yes',
        0 => 'No',
    ],
    'inverse_display_phone' => [
        'Yes' => 1,
        'No' => 0,
    ],
    'agree' => [
        1 => 'Yes',
        0 => 'No',
    ],
    'inverse_agree' => [
        'Yes' => 1,
        'No' => 0,
    ],
    'point_based_timeshare' => [
        1 => 'Yes',
        0 => 'No',
    ],
    'inverse_point_based_timeshare' => [
        'Yes' => 1,
        'No' => 0,
    ],
    'lock_out_unit' => [
        1 => 'Yes',
        0 => 'No',
    ],
    'inverse_lock_out_unit' => [
        'Yes' => 1,
        'No' => 0,
    ],
    'variable' => [
        1 => 'Yes',
        0 => 'No',
    ],
    'inverse_variable' => [
        'Yes' => 1,
        'No' => 0,
    ],
    'exchange_timeshare' => [
        1 => 'Yes',
        0 => 'No',
    ],
    'inverse_exchange_timeshare' => [
        'Yes' => 1,
        'No' => 0,
    ],
    'rental_price_negotiable' => [
        1 => 'Yes',
        0 => 'No',
    ],
    'inverse_rental_price_negotiable' => [
        'Yes' => 1,
        'No' => 0,
    ],
    'is_available_for_sale' => [
        1 => 'Yes',
        0 => 'No',
    ],
    'inverse_is_available_for_sale' => [
        'Yes' => 1,
        'No' => 0,
    ],
    'vacation_property_type' => [
        1 => 'Timeshare',
        2 => 'Owner Property',
    ],
    'inverse_vacation_property_type' => [
        'Timeshare' => 1,
        'Owner Property' => 2,
    ],
    'ownership_type' => [
        1 => 'Deed',
        2 => 'Lease',
        3 => 'Points',
    ],
    'inverse_ownership_type' => [
        'Deed' => 1,
        'Lease' => 2,
        'Points' => 3,
    ],
    'basement' => [
        1 => 'Finished',
        2 => 'Partially finished',
        3 => 'Unfinished',
        4 => 'None',
    ],
    'inverse_basement' => [
        'Finished' => 1,
        'Partially finished' => 2,
        'Unfinished' => 3,
        'None' => 4,
    ],
    'available_weeks' => [
        1 => 'Sunday',
        2 => 'Monday',
        3 => 'Tuesday',
        4 => 'Wednesday',
        5 => 'Thursday',
        6 => 'Friday',
        7 => 'Saturday',
    ],
    'inverse_available_weeks' => [
        'Sunday' => 1,
        'Monday' => 2,
        'Tuesday' => 3,
        'Wednesday' => 4,
        'Thursday' => 5,
        'Friday' => 6,
        'Saturday' => 7,
    ],
    'home_type' => [
        1 => 'Single Family Home',
        2 => 'Condominium',
        3 => 'Manufactured',
        4 => 'Townhouse',
        5 => 'Multi-Family',
        6 => 'Coop Unit',
        7 => 'Vacant Land',
        8 => 'Other',
    ],
    'inverse_home_type' => [
        'Single Family Home' => 1,
        'Condominium' => 2,
        'Manufactured' => 3,
        'Townhouse' => 4,
        'Multi-Family' => 5,
        'Coop Unit' => 6,
        'Vacant Land' => 7,
        'Other' => 8,
    ],
    'home_type_xmlfeed' => [1 => "SingleFamily", "Condo", "Manufactured", "Townhouse",
        "MultiFamily", "Coop", "VacantLand", "Other"],
    'lease_terms_available' => [
        1 => 'Month-To-Month',
        2 => '< 6 Months',
        3 => '6 - 12 Months',
        4 => '> 1 Year',
    ],
    'inverse_lease_terms_available' => [
        'Month-To-Month' => 1,
        '< 6 Months' => 2,
        '6 - 12 Months' => 3,
        '> 1 Year' => 4,
    ],
    'session_question_type' => [
        1 => 'Radio',
        2 => 'Checkbox',
    ],
    'inverse_session_question_type' => [
        'Radio' => 1,
        'Checkbox' => 2,
    ],
    'closing_cost_requested' => [
        1 => 'Yes',
        0 => 'No',
    ],
    'inverse_closing_cost_requested' => [
        'Yes' => 1,
        'No' => 0,
    ],
    'any_contingencies' => [
        1 => 'Yes',
        0 => 'No',
    ],
    'inverse_any_contingencies' => [
        'Yes' => 1,
        'No' => 0,
    ],
    'qualification_documents' => [
        1 => 'Pre Qualified',
        2 => 'Pre Approved',
        3 => 'Not Approved',
        4 => 'Cash Buyer',
    ],
    'inverse_qualification_documents' => [
        'Pre Qualified' => 1,
        'Pre Approved' => 2,
        'Not Approved' => 3,
        'Cash Buyer' => 4,
    ],
    'offer_status' => [
        0 => 'pending',
        1 => 'accepted',
        2 => 'rejected_by_seller',
        3 => 'rejected_by_buyer',
        5 => 'user_deleted'
    ],
    'inverse_offer_status' => [
        'pending' => 0,
        'accepted' => 1,
        'rejected_by_seller' => 2,
        'rejected_by_buyer' => 3,
        'user_deleted' => 5
    ],
    'rent_offer_status' => [
        0 => 'pending',
        1 => 'accepted',
        2 => 'rejected_by_landlord',
        3 => 'rejected_by_buyer',
        5 => 'user_deleted'
    ],
    'inverse_rent_offer_status' => [
        'pending' => 0,
        'accepted' => 1,
        'rejected_by_landlord' => 2,
        'rejected_by_tenant' => 3,
        'user_deleted' => 5
    ],
    'counter_offer_status' => [
        1 => 'Counter',
        2 => 'Declined',
        3 => 'Accepted',
    ],
    'inverse_counter_offer_status' => [
        'counter' => 1,
        'declined' => 2,
        'accepted' => 3,
    ],
    'offer_open_close' => [
        'open' => 0,
        'close' => 1
    ],
    'network_request' => [
        0 => 'pending',
        1 => 'accepted',
    ],
    'inverse_network_request' => [
        'pending' => 0,
        'accepted' => 1,
    ],
    'signer_status' => [
        0 => 'Inactive',
        1 => 'Active',
    ],
    'inverse_signer_status' => [
        'Inactive' => 0,
        'Active' => 1,
    ],
    'beds' => [
        1 => 1,
        2 => 2,
        3 => 3,
        4 => 4,
        5 => 5,
        6 => 6,
        7 => 7,
        8 => 8,
        9 => 9,
        10 => 10,
        11 => '10+',
    ],
    'inverse_beds' => [
        1 => 1,
        2 => 2,
        3 => 3,
        4 => 4,
        5 => 5,
        6 => 6,
        7 => 7,
        8 => 8,
        9 => 9,
        10 => 10,
        11 => '10+',
    ],
    'sleeps' => [
        1 => "0-2",
        2 => "2-4",
        3 => "4-6",
        4 => "6-8",
        5 => "8-10",
        6 => "10-12",
        7 => "12-14",
        8 => "14-16",
        9 => "16-18",
        10 => "18-20",
        111 => "20+",
    ],
    'inverse_sleeps' => [
        "0-2" => 1,
        "2-4" => 2,
        "4-6" => 3,
        "6-8" => 4,
        "8-10" => 5,
        "10-12" => 6,
        "12-14" => 7,
        "14-16" => 8,
        "16-18" => 9,
        "18-20" => 10,
        "20+" => 11,
    ],
    'baths' => [
        1 => 0.5,
        2 => 1,
        3 => 1.5,
        4 => 2,
        5 => 2.5,
        6 => 3,
        7 => 3.5,
        8 => "4+",
    ],
    'inverse_baths' => [
        0.5 => 1,
        1 => 2,
        1.5 => 3,
        2 => 4,
        2.5 => 5,
        3 => 6,
        3.5 => 7,
        "4+" => 8,
    ],
    'home_size' => [
        250 => "250-500",
        501 => "501-750",
        751 => "751-1000",
        1001 => "1001-1250",
        1251 => "1251-1500",
        1501 => "1501-1750",
        1751 => "1751-2000",
        2001 => "2001-2250",
        2251 => '2251-2500',
        2501 => "2501-3000",
        3001 => "3001-3250",
        3251 => "3251-3500",
        3501 => "3501-3750",
        3751 => "3751-4000",
        4001 => "4001-4250",
        4251 => '4251-4500',
        4501 => "4501-4750",
        4751 => '4751-5000',
        5001 => "5001-5250+",
    ],
//    'inverse_baths' => [
//        250-500=>250,
//        500-750=>500,
//        750-1000 =>750,
//         1000-1250=>1000,
//        1250-1500=>1250,
//        1500-1750 =>1500,
//        1750-2000 => 1750,
//        2000 => 2000-2250,
//        2250 => 2250-2500,
//        2500 => 2500-3000,
//        3000 => 3000-3250,
//        3250 => 3250-3500,
//        3500 => 3500-3750,
//        3750 => 3750-4000,
//        4000 => 4000-4250,
//        4250 => 4250-4500,
//        4500 => 4500-4750,
//        4750 => 4750-5000,
//        5000 => "5000-5250+",
//    ],
    'pets_type' => [
        1 => 'Dogs',
        2 => 'Cats',
        3 => 'Other',
    ],
    'inverse_pets_type' => [
        'Cats' => 1,
        'Dogs' => 2,
        'Other' => 3,
    ],
    'lead_based' => [
        1 => true,
        2 => false,
    ],
    'inverse_lead_based' => [
        true => 1,
        false => 2,
    ],
    'lead_opportunity' => [
        1 => '10-day opportunity',
        2 => 'Waived the opportunity',
    ],
    'inverse_lead_opportunity' => [
        '10-day opportunity' => 1,
        'Waived the opportunity' => 2,
    ],
    'lead_based_report' => [
        1 => true,
        2 => false,
    ],
    'inverse_lead_based_report' => [
        true => 1,
        false => 2,
    ],
//    'lead_opportunity' => [
//        1 => true,
//        2 => false,
//    ],
//    'inverse_lead_opportunity' => [
//        true => 1,
//        false => 2,
//    ],
    'epa' => [
        1 => 'readepa',
        2 => 'receivedcopies',
    ],
    'inverse_epa' => [
        'readepa' => 1,
        'receivedcopies' => 2,
    ],
    'signature_type' => [
        1 => 'lead based',
        2 => 'property disclaimer',
        3 => 'advisory to buyers and sellers',
        4 => 'sale agreement',
        5 => 'VA FHA loan addendum',
        6 => 'post closing occupancy agreement',
    ],
    'inverse_signature_type' => [
        'lead based' => 1,
        'property disclaimer' => 2,
        'advisory to buyers and sellers' => 3,
        'sale agreement' => 4,
        'VA FHA loan addendum' => 5,
        'post closing occupancy agreement' => 6,
        'default'=>7,
    ],
    'signature_type_rent' => [
        1 => 'lead based',
        2 => 'property disclaimer',
        3 => 'rent agreement',
    ],
    'inverse_signature_type_rent' => [
        'lead based' => 1,
        'property disclaimer' => 2,
        'rent agreement' => 3,
    ],
    'offer_signature' => [
        'false' => 0,
        'true' => 1
    ],
    'seller_questionnaire' => [
        1 => 'Yes',
        2 => 'No',
    ],
    'inverse_seller_questionnaire' => [
        'Yes' => 1,
        'No' => 2,
    ],
    'common_yes_no' => [
        1 => 'Yes',
        2 => 'No',
    ],
    'inverse_common_yes_no' => [
        'Yes' => 1,
        'No' => 2,
    ],
    'property_condition_disclaimer' => [
        1 => 'Yes',
        2 => 'No',
        3 => 'NA',
    ],
    'inverse_property_condition_disclaimer' => [
        'Yes' => 1,
        'No' => 2,
        'NA' => 3,
    ],
    'property_disclaimer_occupy' => [
        1 => 'Seller occupies property',
        2 => 'Seller does not occupy property',
    ],
    'inverse_property_disclaimer_occupy' => [
        'Seller occupies property' => 1,
        'Seller does not occupy property' => 2,
    ],
    'property_disclaimer_propertyis' => [
        1 => 'Site-built home',
        2 => 'Non-site-built home',
    ],
    'inverse_property_disclaimer_propertyis' => [
        'Site-built Home' => 1,
        'Non-site-built Home' => 2,
    ],
    'property_disclaimer_pool' => [
        1 => 'In-ground',
        2 => 'Above-ground',
    ],
    'inverse_property_disclaimer_pool' => [
        'In-ground' => 1,
        'Above-ground' => 2,
    ],
    'property_disclaimer_garage' => [
        1 => 'Attached',
        2 => 'Not Attached',
    ],
    'inverse_property_disclaimer_garage' => [
        'Attached' => 1,
        'Not Attached' => 2,
    ],
    'property_disclaimer_best_knowledge' => [
        1 => 'Yes',
        2 => 'No',
    ],
    'inverse_property_disclaimer_best_knowledge' => [
        'Yes' => 1,
        'No' => 2,
    ],
    'update_sale_agreement_by_seller' => [
        1 => 'Lead-Based Paint Disclosure',
        2 => 'Occupancy Agreement',
        3 => 'VA/FHA Loan Addendum',
        4 => 'Advisory to Buyers and Sellers',
        5 => 'Addendum',
        6 => 'Other',
        7 => 'Tennessee Residential Property Condition Disclosure',
    ],
    'inverse_update_sale_agreement_by_seller' => [
        'Lead-Based Paint Disclosure' => 1,
        'Occupancy Agreement' => 2,
        'VA/FHA Loan Addendum' => 3,
        'Advisory to Buyers and Sellers' => 4,
        'Addendum' => 5,
        'Other' => 6,
        'Tennessee Residential Property Condition Disclosure' => 7,
    ],
    'blog_comment' => [
        'unapproved' => 0,
        'approved' => 1
    ],
    'instructions' => 999999,
    'contract_tool_status' => [
        0 => 'False',
        1 => 'True'
    ],
    'contract_tool_status_inverse' => [
        'False' => 0,
        'True' => 1
    ],
    'joint_coowner' => [
        'Yes' => 1,
        'No' => 2
    ],
     'show_post_closing_form' => [
        'Yes' => 1,
        'No' => 2
    ],
];
